// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV0QBTnhYn2UHvXvAxJfxgUwn9Ts9Ejr0',
    appId: '1:412346781266:web:a0793a823817b98399d98b',
    messagingSenderId: '412346781266',
    projectId: 'shopsizzle-35b78',
    authDomain: 'shopsizzle-35b78.firebaseapp.com',
    storageBucket: 'shopsizzle-35b78.appspot.com',
    measurementId: 'G-WZG6W82PE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCASEPPo3UG6QUhrDB8ZSmaEvnvndXUgJs',
    appId: '1:412346781266:android:4eab1b695f67266299d98b',
    messagingSenderId: '412346781266',
    projectId: 'shopsizzle-35b78',
    storageBucket: 'shopsizzle-35b78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFM3KeMC__v19-FMHZUyh-FcrwVQjEXNg',
    appId: '1:412346781266:ios:0d89d8627975023099d98b',
    messagingSenderId: '412346781266',
    projectId: 'shopsizzle-35b78',
    storageBucket: 'shopsizzle-35b78.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFM3KeMC__v19-FMHZUyh-FcrwVQjEXNg',
    appId: '1:412346781266:ios:0d89d8627975023099d98b',
    messagingSenderId: '412346781266',
    projectId: 'shopsizzle-35b78',
    storageBucket: 'shopsizzle-35b78.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV0QBTnhYn2UHvXvAxJfxgUwn9Ts9Ejr0',
    appId: '1:412346781266:web:9e605ad80d29087099d98b',
    messagingSenderId: '412346781266',
    projectId: 'shopsizzle-35b78',
    authDomain: 'shopsizzle-35b78.firebaseapp.com',
    storageBucket: 'shopsizzle-35b78.appspot.com',
    measurementId: 'G-LEF464G0C5',
  );
}
